### PR TITLE
Add SetBoxType()

### PR DESCRIPTION
**Pull request by mgord9518**
From Fl::set_boxtype(), allowing the creation of custom widget drawing,
along with replacing all BoxTypes with their respective ints to reduce
C++ calling. Also add Image.Draw() as it's needed to draw images
manually for theming

### CODE REVIEW

**Comment by pwiecz** [comment]
FLTK api is really bad for creating bindings here...
One one hand we can pass different drawing functions for different BoxTypes, on the other hand there's no userinfo or boxtype parameter passed to the box drawing function.
I can see no way to specify more than one custom box type. :(
I'll file an issue to the FLTK library, although I'm not sure if they care that much about foreign language bindings...

I'm merging the pull request, but maybe I'll keep thinking if there's a better way to do it...

**Comment by mgord9518** [comment]
I was thinking about that after submitting, maybe a func array is the way to go?

**Comment by pwiecz** [comment]
Even if we use func array, I see no way to know which function from the array to call.

**Comment by mgord9518** [comment]
Oof, yeah. I've been messing with it a bit trying to pass the current box number from FLTK back to the Go code and I can't get it to work because the number only gets set on initial setup, not every widget draw. I wonder how other bindings do it.

Maybe it is possible without passing the box type in Fl::set_boxtype, but it sure isn't easy.

I just stared learning FLTK and it seems great so far but this is one hell of a roadblock...

**Pull request merged**
