### PR TITLE
Implement TextDisplay.SetWrapMode()

### PR DESCRIPTION
**Pull request by mgord9518**

### CODE REVIEW

**Comment by pwiecz** [comment]
Do you think you could add a new WrapMode type for the wrapMode parameter, like BoxType (enumerations.go) being a type of the boxType parameter of Box (box.go)?

**Comment by mgord9518** [comment]
Yeah, I can do that real quick. Question though, why are all the constants uppercase in the Go bindings instead of pascal case? Also, when I add it should it still call the C++ code or just add the constants in pure Go?

Eg:
```
type WrapType int
const (
    WRAP_NONE = 0
    WRAP_AT_COLUMN = 1
...
)
```

I think pure Go would be more maintainable and would probably run faster as it's working through less layers of abstraction

**Comment by pwiecz** [comment]
There's no good reason for them being snake case.
I guess it shows my lack of knowledge of Go style guide and its roots in an old fltk bindings: https://github.com/zot/go-fltk/blob/master/src/fltk.go
Most probably we'll switch to PascalCase sooner or later. But right now for consistency we need to stick to the snake case. :(
And sur, use the constants.

**Comment by pwiecz** [comment]
Thanks a lot for the work! :)

**Pull request merged**
