### PR TITLE
Some additions

### PR DESCRIPTION
**Pull request by tomet**
I added some functions that i needed for a project.

### CODE REVIEW

**Review by pwiecz — COMMENTED** [review]
Was this change meant to be sent?

**Comment by tomet** [comment]
Yes, maybe my additions can be merged. I only added some functions that are part of the c++-fltk library (e.g. Fl::menu_linespacing(), Fl_Button->shortcut(), ...).

I needed this features for a private hobby-project. Maybe they are useful for you too.

The modification of go.mod was only for my project and should not be merged ;-)

**Comment by pwiecz** [comment]
Thanks for the pull request!
I'm on vacation now, I'll look at it next week.

**Comment by tomet** [comment]
Thank you!

I wish you nice holidays 😀

Am Mi., 3. Mai 2023 um 06:56 Uhr schrieb pwiecz ***@***.***>:

**Comment by pwiecz** [comment]
Hi, I've modified a bit your code and added the slightly modified version in commit cc265bffe76790153523b34abae5b6000b1e929b

**Pull request closed without merging**
